In [21]:
import talib as ta
import pandas as pd
import numpy as np
from mysql import connector
from mysql import connector

def getConn():
    return connector.connect(user='Mercury', password='Mercury@1234', host='104.211.223.42', database='optionspakshi', auth_plugin='mysql_native_password')

In [22]:
df = pd.read_sql_query("select * from eoddata where SYMBOL='BANKNIFTY' order by adate", getConn())
df.to_csv ("basic.csv")
df= pd.read_csv ("basic.csv")
df

,Unnamed: 0,EODDATAID,ADATE,SYMBOL,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TIMESTAMP,TOTALTRADES
0,0,435571593,2019-04-02,BANKNIFTY,30450.10,30452.90,30155.85,30354.25,NaN,NaN,196482019,5205.38,2019-04-02,NaN
1,1,435581593,2019-04-03,BANKNIFTY,30440.85,30602.55,30036.25,30093.30,NaN,NaN,193071867,5203.95,2019-04-03,NaN
2,2,435591593,2019-04-04,BANKNIFTY,30147.30,30245.70,29809.90,29904.90,NaN,NaN,199631082,5460.27,2019-04-04,NaN
3,3,435601593,2019-04-05,BANKNIFTY,30002.85,30174.00,29850.00,30084.65,NaN,NaN,154141037,4130.84,2019-04-05,NaN
4,4,435631593,2019-04-08,BANKNIFTY,30201.50,30232.05,29716.60,29845.30,NaN,NaN,147201421,3687.89,2019-04-08,NaN
5,5,435641593,2019-04-09,BANKNIFTY,29901.50,30165.05,29703.55,30113.85,NaN,NaN,165462138,4788.34,2019-04-09,NaN
6,6,435651593,2019-04-10,BANKNIFTY,29916.60,30155.75,29768.10,29803.50,NaN,NaN,165250173,9946.96,2019-04-10,NaN
7,7,435661593,2019-04-11,BANKNIFTY,29841.85,29852.25,29640.25,29786.10,NaN,NaN,108247929,3168.46,2019-04-11,NaN
8,8,435671593,2019-04-12,BANKNIFTY,29780.55,30000.95,29707.00,29938.55,NaN,NaN,104858970,3137.74,2019-04-12,NaN
9,9,435701593,2019-04-15,BANKNIFTY,29983.50,30163.10,29919.10,30104.25,NaN,NaN,90613632,3071.18,2019-04-15,NaN
10,10,435711593,2019-04-16,BANKNIFTY,30236.25,30590.95,30228.20,30531.35,NaN,NaN,117822281,4223.74,2019-04-16,NaN
11,11,435731593,2019-04-18,BANKNIFTY,30656.50,30669.80,30142.20,30223.40,NaN,NaN,141697748,4610.68,2019-04-18,NaN
12,12,435771593,2019-04-22,BANKNIFTY,30282.50,30289.90,29647.55,29687.95,NaN,NaN,132778018,4647.04,2019-04-22,NaN
13,13,435781593,2019-04-23,BANKNIFTY,29761.95,29906.50,29455.45,29479.70,NaN,NaN,145857126,4502.93,2019-04-23,NaN
14,14,435791593,2019-04-24,BANKNIFTY,29550.50,29914.85,29435.05,29860.80,NaN,NaN,129529258,4477.27,2019-04-24,NaN
15,15,435801593,2019-04-25,BANKNIFTY,29927.05,30057.70,29511.95,29561.35,NaN,NaN,201016367,6526.09,2019-04-25,NaN
16,16,435811593,2019-04-26,BANKNIFTY,29764.85,30048.20,29563.15,30013.50,NaN,NaN,158188658,5736.29,2019-04-26,NaN
17,17,435851593,2019-04-30,BANKNIFTY,29920.40,29920.40,29550.05,29764.80,NaN,NaN,362563145,9257.75,2019-04-30,NaN
18,18,435871593,2019-05-02,BANKNIFTY,29699.80,29919.35,29638.80,29708.60,NaN,NaN,242309997,6830.49,2019-05-02,NaN
19,19,435881593,2019-05-03,BANKNIFTY,29811.65,30121.75,29795.10,29954.15,NaN,NaN,181379119,5248.10,2019-05-03,NaN
20,20,435911593,2019-05-06,BANKNIFTY,29626.50,29757.40,29528.60,29618.45,NaN,NaN,188230212,4787.11,2019-05-06,NaN
21,21,435921593,2019-05-07,BANKNIFTY,29749.55,29835.50,29244.25,29288.20,NaN,NaN,180581999,5340.05,2019-05-07,NaN
22,22,435931593,2019-05-08,BANKNIFTY,29261.30,29261.30,28951.35,28994.40,NaN,NaN,179421775,4926.02,2019-05-08,NaN
23,23,435941593,2019-05-09,BANKNIFTY,28893.95,29040.30,28784.65,28884.60,NaN,NaN,206029474,5196.87,2019-05-09,NaN
24,24,435951593,2019-05-10,BANKNIFTY,28927.60,29202.85,28900.10,29040.50,NaN,NaN,223514610,6070.63,2019-05-10,NaN
25,25,435981593,2019-05-13,BANKNIFTY,29026.65,29049.05,28621.10,28659.95,NaN,NaN,253600119,5356.35,2019-05-13,NaN
26,26,435991593,2019-05-14,BANKNIFTY,28718.75,29058.30,28582.60,28829.20,NaN,NaN,256593306,6110.47,2019-05-14,NaN
27,27,436001593,2019-05-15,BANKNIFTY,28925.45,28983.15,28555.15,28616.45,NaN,NaN,218778407,5126.91,2019-05-15,NaN
28,28,436011593,2019-05-16,BANKNIFTY,28625.90,28947.60,28525.45,28855.30,NaN,NaN,189440058,4501.11,2019-05-16,NaN
29,29,436021593,2019-05-17,BANKNIFTY,28881.40,29559.45,28856.00,29450.15,NaN,NaN,257111157,6489.10,2019-05-17,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,90,436911593,2019-08-14,BANKNIFTY,27885.50,28107.05,27726.65,28019.20,NaN,NaN,290413445,5104.33,NaN,NaN
91,91,436971593,2019-08-20,BANKNIFTY,28163.55,28215.40,27839.65,27982.45,NaN,NaN,288236399,5073.04,NaN,NaN
92,92,436981593,2019-08-21,BANKNIFTY,28021.00,28098.90,27666.20,27719.05,NaN,NaN,358841104,5315.64,NaN,NaN
93,93,436991593,2019-08-22,BANKNIFTY,27690.05,27690.05,26975.55,27034.20,NaN,NaN,465070847,6452.46,NaN,NaN
94,94,437001593,2019-08-23,BANKNIFTY,26835.35,27207.30,26560.60,26958.65,NaN,NaN,485538647,7843.57,NaN,NaN
95,95,437031593,2019-08-26,BANKNIFTY,27663.95,27995.25,26859.35,27951.35,NaN,NaN,519219181,8927.81,NaN,NaN
96,96,437041593,2019-08-27,BANKNIFTY,28106.30,28277.70,27960.80,28126.15,NaN,NaN,386839458,7802.00,NaN,NaN
97,97,437051593,2019-08-28,BANKNIFTY,28080.25,28095.55,27634.65,27804.30,NaN,NaN,384111651,6674.30,NaN,NaN
98,98,437061593,2019-08-29,BANKNIFTY,27694.95,27719.05,27239.95,27305.20,NaN,NaN,377438481,7339.26,NaN,NaN
99,99,437071593,2019-08-30,BANKNIFTY,27407.90,27586.50,27121.95,27427.85,NaN,NaN,427077225,8056.50,NaN,NaN
100,100,437111593,2019-09-03,BANKNIFTY,27239.20,27247.05,26742.60,26824.15,NaN,NaN,392427883,6171.33,NaN,NaN
101,101,437121593,2019-09-04,BANKNIFTY,26785.95,27278.70,26641.35,27123.85,NaN,NaN,309520214,5990.87,NaN,NaN
102,102,437131593,2019-09-05,BANKNIFTY,27086.95,27243.95,26815.40,26919.70,NaN,NaN,327083693,5826.31,2019-09-05,NaN
103,103,437141593,2019-09-06,BANKNIFTY,26986.50,27311.05,26950.55,27247.90,NaN,NaN,251986487,4874.57,2019-09-06,NaN
104,104,437171593,2019-09-09,BANKNIFTY,27240.35,27565.55,26993.90,27504.65,NaN,NaN,286110458,5197.20,2019-09-09,NaN
105,105,437191593,2019-09-11,BANKNIFTY,27639.05,27829.65,27551.65,27776.20,NaN,NaN,467414755,6677.77,2019-09-11,NaN
106,106,437201593,2019-09-12,BANKNIFTY,27870.80,28062.30,27764.70,27818.50,NaN,NaN,377820739,6469.22,2019-09-12,NaN
107,107,437211593,2019-09-13,BANKNIFTY,27772.00,28126.85,27573.45,28098.75,NaN,NaN,438497830,6752.69,2019-09-13,NaN
108,108,437241593,2019-09-16,BANKNIFTY,27868.00,28066.70,27798.85,27855.00,NaN,NaN,234062573,4463.98,2019-09-16,NaN
109,109,437251593,2019-09-17,BANKNIFTY,27765.10,27851.40,27047.95,27131.75,NaN,NaN,277762547,5449.45,2019-09-17,NaN
110,110,437261593,2019-09-18,BANKNIFTY,27304.70,27414.45,27088.80,27172.65,NaN,NaN,307775512,5314.41,2019-09-18,NaN
111,111,437271593,2019-09-19,BANKNIFTY,27175.45,27175.45,26643.00,26757.65,NaN,NaN,450436905,6050.19,2019-09-19,NaN
112,112,437281593,2019-09-20,BANKNIFTY,26878.65,29418.95,26727.55,28981.55,NaN,NaN,844582360,18185.99,2019-09-20,NaN
113,113,437311593,2019-09-23,BANKNIFTY,30039.40,30801.30,29776.30,30566.20,NaN,NaN,552171387,14401.90,2019-09-23,NaN
114,114,437321593,2019-09-24,BANKNIFTY,30432.00,30668.10,29889.55,30183.10,NaN,NaN,348810197,8157.62,2019-09-24,NaN
115,115,437331593,2019-09-25,BANKNIFTY,30029.05,30067.60,29470.10,29586.05,NaN,NaN,352814285,8112.37,2019-09-25,NaN
116,116,437341593,2019-09-26,BANKNIFTY,29640.55,30718.35,29627.00,30002.60,NaN,NaN,540435004,11367.60,2019-09-26,NaN
117,117,437351593,2019-09-27,BANKNIFTY,29974.95,30112.65,29711.35,29876.65,NaN,NaN,464096458,7011.82,2019-09-27,NaN
118,118,437381593,2019-09-30,BANKNIFTY,29674.80,29754.40,28943.45,29103.15,NaN,NaN,580252025,9447.47,2019-09-30,NaN
119,119,437391593,2019-10-01,BANKNIFTY,29226.15,29526.40,28077.35,28725.50,NaN,NaN,1187313940,15321.69,2019-10-01,NaN

### Get the data from EODData

In [18]:
df.round(1)
df=df.drop(['LAST', 'PREVCLOSE', 'TIMESTAMP', 'TOTALTRADES'], axis=1)
df

,Unnamed: 0,EODDATAID,ADATE,SYMBOL,OPEN,HIGH,LOW,CLOSE,TOTTRDQTY,TOTTRDVAL
0,0,435571593,2019-04-02,BANKNIFTY,30450.10,30452.90,30155.85,30354.25,196482019,5205.38
1,1,435581593,2019-04-03,BANKNIFTY,30440.85,30602.55,30036.25,30093.30,193071867,5203.95
2,2,435591593,2019-04-04,BANKNIFTY,30147.30,30245.70,29809.90,29904.90,199631082,5460.27
3,3,435601593,2019-04-05,BANKNIFTY,30002.85,30174.00,29850.00,30084.65,154141037,4130.84
4,4,435631593,2019-04-08,BANKNIFTY,30201.50,30232.05,29716.60,29845.30,147201421,3687.89
5,5,435641593,2019-04-09,BANKNIFTY,29901.50,30165.05,29703.55,30113.85,165462138,4788.34
6,6,435651593,2019-04-10,BANKNIFTY,29916.60,30155.75,29768.10,29803.50,165250173,9946.96
7,7,435661593,2019-04-11,BANKNIFTY,29841.85,29852.25,29640.25,29786.10,108247929,3168.46
8,8,435671593,2019-04-12,BANKNIFTY,29780.55,30000.95,29707.00,29938.55,104858970,3137.74
9,9,435701593,2019-04-15,BANKNIFTY,29983.50,30163.10,29919.10,30104.25,90613632,3071.18
10,10,435711593,2019-04-16,BANKNIFTY,30236.25,30590.95,30228.20,30531.35,117822281,4223.74
11,11,435731593,2019-04-18,BANKNIFTY,30656.50,30669.80,30142.20,30223.40,141697748,4610.68
12,12,435771593,2019-04-22,BANKNIFTY,30282.50,30289.90,29647.55,29687.95,132778018,4647.04
13,13,435781593,2019-04-23,BANKNIFTY,29761.95,29906.50,29455.45,29479.70,145857126,4502.93
14,14,435791593,2019-04-24,BANKNIFTY,29550.50,29914.85,29435.05,29860.80,129529258,4477.27
15,15,435801593,2019-04-25,BANKNIFTY,29927.05,30057.70,29511.95,29561.35,201016367,6526.09
16,16,435811593,2019-04-26,BANKNIFTY,29764.85,30048.20,29563.15,30013.50,158188658,5736.29
17,17,435851593,2019-04-30,BANKNIFTY,29920.40,29920.40,29550.05,29764.80,362563145,9257.75
18,18,435871593,2019-05-02,BANKNIFTY,29699.80,29919.35,29638.80,29708.60,242309997,6830.49
19,19,435881593,2019-05-03,BANKNIFTY,29811.65,30121.75,29795.10,29954.15,181379119,5248.10
20,20,435911593,2019-05-06,BANKNIFTY,29626.50,29757.40,29528.60,29618.45,188230212,4787.11
21,21,435921593,2019-05-07,BANKNIFTY,29749.55,29835.50,29244.25,29288.20,180581999,5340.05
22,22,435931593,2019-05-08,BANKNIFTY,29261.30,29261.30,28951.35,28994.40,179421775,4926.02
23,23,435941593,2019-05-09,BANKNIFTY,28893.95,29040.30,28784.65,28884.60,206029474,5196.87
24,24,435951593,2019-05-10,BANKNIFTY,28927.60,29202.85,28900.10,29040.50,223514610,6070.63
25,25,435981593,2019-05-13,BANKNIFTY,29026.65,29049.05,28621.10,28659.95,253600119,5356.35
26,26,435991593,2019-05-14,BANKNIFTY,28718.75,29058.30,28582.60,28829.20,256593306,6110.47
27,27,436001593,2019-05-15,BANKNIFTY,28925.45,28983.15,28555.15,28616.45,218778407,5126.91
28,28,436011593,2019-05-16,BANKNIFTY,28625.90,28947.60,28525.45,28855.30,189440058,4501.11
29,29,436021593,2019-05-17,BANKNIFTY,28881.40,29559.45,28856.00,29450.15,257111157,6489.10
...,...,...,...,...,...,...,...,...,...,...
90,90,436911593,2019-08-14,BANKNIFTY,27885.50,28107.05,27726.65,28019.20,290413445,5104.33
91,91,436971593,2019-08-20,BANKNIFTY,28163.55,28215.40,27839.65,27982.45,288236399,5073.04
92,92,436981593,2019-08-21,BANKNIFTY,28021.00,28098.90,27666.20,27719.05,358841104,5315.64
93,93,436991593,2019-08-22,BANKNIFTY,27690.05,27690.05,26975.55,27034.20,465070847,6452.46
94,94,437001593,2019-08-23,BANKNIFTY,26835.35,27207.30,26560.60,26958.65,485538647,7843.57
95,95,437031593,2019-08-26,BANKNIFTY,27663.95,27995.25,26859.35,27951.35,519219181,8927.81
96,96,437041593,2019-08-27,BANKNIFTY,28106.30,28277.70,27960.80,28126.15,386839458,7802.00
97,97,437051593,2019-08-28,BANKNIFTY,28080.25,28095.55,27634.65,27804.30,384111651,6674.30
98,98,437061593,2019-08-29,BANKNIFTY,27694.95,27719.05,27239.95,27305.20,377438481,7339.26
99,99,437071593,2019-08-30,BANKNIFTY,27407.90,27586.50,27121.95,27427.85,427077225,8056.50
100,100,437111593,2019-09-03,BANKNIFTY,27239.20,27247.05,26742.60,26824.15,392427883,6171.33
101,101,437121593,2019-09-04,BANKNIFTY,26785.95,27278.70,26641.35,27123.85,309520214,5990.87
102,102,437131593,2019-09-05,BANKNIFTY,27086.95,27243.95,26815.40,26919.70,327083693,5826.31
103,103,437141593,2019-09-06,BANKNIFTY,26986.50,27311.05,26950.55,27247.90,251986487,4874.57
104,104,437171593,2019-09-09,BANKNIFTY,27240.35,27565.55,26993.90,27504.65,286110458,5197.20
105,105,437191593,2019-09-11,BANKNIFTY,27639.05,27829.65,27551.65,27776.20,467414755,6677.77
106,106,437201593,2019-09-12,BANKNIFTY,27870.80,28062.30,27764.70,27818.50,377820739,6469.22
107,107,437211593,2019-09-13,BANKNIFTY,27772.00,28126.85,27573.45,28098.75,438497830,6752.69
108,108,437241593,2019-09-16,BANKNIFTY,27868.00,28066.70,27798.85,27855.00,234062573,4463.98
109,109,437251593,2019-09-17,BANKNIFTY,27765.10,27851.40,27047.95,27131.75,277762547,5449.45
110,110,437261593,2019-09-18,BANKNIFTY,27304.70,27414.45,27088.80,27172.65,307775512,5314.41
111,111,437271593,2019-09-19,BANKNIFTY,27175.45,27175.45,26643.00,26757.65,450436905,6050.19
112,112,437281593,2019-09-20,BANKNIFTY,26878.65,29418.95,26727.55,28981.55,844582360,18185.99
113,113,437311593,2019-09-23,BANKNIFTY,30039.40,30801.30,29776.30,30566.20,552171387,14401.90
114,114,437321593,2019-09-24,BANKNIFTY,30432.00,30668.10,29889.55,30183.10,348810197,8157.62
115,115,437331593,2019-09-25,BANKNIFTY,30029.05,30067.60,29470.10,29586.05,352814285,8112.37
116,116,437341593,2019-09-26,BANKNIFTY,29640.55,30718.35,29627.00,30002.60,540435004,11367.60
117,117,437351593,2019-09-27,BANKNIFTY,29974.95,30112.65,29711.35,29876.65,464096458,7011.82
118,118,437381593,2019-09-30,BANKNIFTY,29674.80,29754.40,28943.45,29103.15,580252025,9447.47
119,119,437391593,2019-10-01,BANKNIFTY,29226.15,29526.40,28077.35,28725.50,1187313940,15321.69

In [20]:
n=10
field="CLOSE"
df["RSI"] = pd.Series(ta.RSI(df[field].values, n), index = df.index, name='RSI%s' % str(4))
df

,Unnamed: 0,EODDATAID,ADATE,SYMBOL,OPEN,HIGH,LOW,CLOSE,TOTTRDQTY,TOTTRDVAL,RSI
0,0,435571593,2019-04-02,BANKNIFTY,30450.10,30452.90,30155.85,30354.25,196482019,5205.38,NaN
1,1,435581593,2019-04-03,BANKNIFTY,30440.85,30602.55,30036.25,30093.30,193071867,5203.95,NaN
2,2,435591593,2019-04-04,BANKNIFTY,30147.30,30245.70,29809.90,29904.90,199631082,5460.27,NaN
3,3,435601593,2019-04-05,BANKNIFTY,30002.85,30174.00,29850.00,30084.65,154141037,4130.84,NaN
4,4,435631593,2019-04-08,BANKNIFTY,30201.50,30232.05,29716.60,29845.30,147201421,3687.89,NaN
5,5,435641593,2019-04-09,BANKNIFTY,29901.50,30165.05,29703.55,30113.85,165462138,4788.34,NaN
6,6,435651593,2019-04-10,BANKNIFTY,29916.60,30155.75,29768.10,29803.50,165250173,9946.96,NaN
7,7,435661593,2019-04-11,BANKNIFTY,29841.85,29852.25,29640.25,29786.10,108247929,3168.46,NaN
8,8,435671593,2019-04-12,BANKNIFTY,29780.55,30000.95,29707.00,29938.55,104858970,3137.74,NaN
9,9,435701593,2019-04-15,BANKNIFTY,29983.50,30163.10,29919.10,30104.25,90613632,3071.18,NaN
10,10,435711593,2019-04-16,BANKNIFTY,30236.25,30590.95,30228.20,30531.35,117822281,4223.74,54.006787
11,11,435731593,2019-04-18,BANKNIFTY,30656.50,30669.80,30142.20,30223.40,141697748,4610.68,46.766146
12,12,435771593,2019-04-22,BANKNIFTY,30282.50,30289.90,29647.55,29687.95,132778018,4647.04,37.145028
13,13,435781593,2019-04-23,BANKNIFTY,29761.95,29906.50,29455.45,29479.70,145857126,4502.93,34.112331
14,14,435791593,2019-04-24,BANKNIFTY,29550.50,29914.85,29435.05,29860.80,129529258,4477.27,43.493151
15,15,435801593,2019-04-25,BANKNIFTY,29927.05,30057.70,29511.95,29561.35,201016367,6526.09,38.684567
16,16,435811593,2019-04-26,BANKNIFTY,29764.85,30048.20,29563.15,30013.50,158188658,5736.29,48.278248
17,17,435851593,2019-04-30,BANKNIFTY,29920.40,29920.40,29550.05,29764.80,362563145,9257.75,44.064620
18,18,435871593,2019-05-02,BANKNIFTY,29699.80,29919.35,29638.80,29708.60,242309997,6830.49,43.119692
19,19,435881593,2019-05-03,BANKNIFTY,29811.65,30121.75,29795.10,29954.15,181379119,5248.10,48.482859
20,20,435911593,2019-05-06,BANKNIFTY,29626.50,29757.40,29528.60,29618.45,188230212,4787.11,42.408736
21,21,435921593,2019-05-07,BANKNIFTY,29749.55,29835.50,29244.25,29288.20,180581999,5340.05,37.300624
22,22,435931593,2019-05-08,BANKNIFTY,29261.30,29261.30,28951.35,28994.40,179421775,4926.02,33.332057
23,23,435941593,2019-05-09,BANKNIFTY,28893.95,29040.30,28784.65,28884.60,206029474,5196.87,31.921755
24,24,435951593,2019-05-10,BANKNIFTY,28927.60,29202.85,28900.10,29040.50,223514610,6070.63,36.181633
25,25,435981593,2019-05-13,BANKNIFTY,29026.65,29049.05,28621.10,28659.95,253600119,5356.35,30.932093
26,26,435991593,2019-05-14,BANKNIFTY,28718.75,29058.30,28582.60,28829.20,256593306,6110.47,35.552831
27,27,436001593,2019-05-15,BANKNIFTY,28925.45,28983.15,28555.15,28616.45,218778407,5126.91,32.514657
28,28,436011593,2019-05-16,BANKNIFTY,28625.90,28947.60,28525.45,28855.30,189440058,4501.11,39.015519
29,29,436021593,2019-05-17,BANKNIFTY,28881.40,29559.45,28856.00,29450.15,257111157,6489.10,51.850448
...,...,...,...,...,...,...,...,...,...,...,...
90,90,436911593,2019-08-14,BANKNIFTY,27885.50,28107.05,27726.65,28019.20,290413445,5104.33,39.013940
91,91,436971593,2019-08-20,BANKNIFTY,28163.55,28215.40,27839.65,27982.45,288236399,5073.04,38.549013
92,92,436981593,2019-08-21,BANKNIFTY,28021.00,28098.90,27666.20,27719.05,358841104,5315.64,35.207686
93,93,436991593,2019-08-22,BANKNIFTY,27690.05,27690.05,26975.55,27034.20,465070847,6452.46,28.157028
94,94,437001593,2019-08-23,BANKNIFTY,26835.35,27207.30,26560.60,26958.65,485538647,7843.57,27.482432
95,95,437031593,2019-08-26,BANKNIFTY,27663.95,27995.25,26859.35,27951.35,519219181,8927.81,46.274627
96,96,437041593,2019-08-27,BANKNIFTY,28106.30,28277.70,27960.80,28126.15,386839458,7802.00,48.867107
97,97,437051593,2019-08-28,BANKNIFTY,28080.25,28095.55,27634.65,27804.30,384111651,6674.30,44.476393
98,98,437061593,2019-08-29,BANKNIFTY,27694.95,27719.05,27239.95,27305.20,377438481,7339.26,38.513903
99,99,437071593,2019-08-30,BANKNIFTY,27407.90,27586.50,27121.95,27427.85,427077225,8056.50,40.685100
100,100,437111593,2019-09-03,BANKNIFTY,27239.20,27247.05,26742.60,26824.15,392427883,6171.33,34.099675
101,101,437121593,2019-09-04,BANKNIFTY,26785.95,27278.70,26641.35,27123.85,309520214,5990.87,39.501221
102,102,437131593,2019-09-05,BANKNIFTY,27086.95,27243.95,26815.40,26919.70,327083693,5826.31,37.193829
103,103,437141593,2019-09-06,BANKNIFTY,26986.50,27311.05,26950.55,27247.90,251986487,4874.57,43.127952
104,104,437171593,2019-09-09,BANKNIFTY,27240.35,27565.55,26993.90,27504.65,286110458,5197.20,47.444181
105,105,437191593,2019-09-11,BANKNIFTY,27639.05,27829.65,27551.65,27776.20,467414755,6677.77,51.747670
106,106,437201593,2019-09-12,BANKNIFTY,27870.80,28062.30,27764.70,27818.50,377820739,6469.22,52.421971
107,107,437211593,2019-09-13,BANKNIFTY,27772.00,28126.85,27573.45,28098.75,438497830,6752.69,56.859897
108,108,437241593,2019-09-16,BANKNIFTY,27868.00,28066.70,27798.85,27855.00,234062573,4463.98,52.158220
109,109,437251593,2019-09-17,BANKNIFTY,27765.10,27851.40,27047.95,27131.75,277762547,5449.45,40.985108
110,110,437261593,2019-09-18,BANKNIFTY,27304.70,27414.45,27088.80,27172.65,307775512,5314.41,41.768896
111,111,437271593,2019-09-19,BANKNIFTY,27175.45,27175.45,26643.00,26757.65,450436905,6050.19,36.329193
112,112,437281593,2019-09-20,BANKNIFTY,26878.65,29418.95,26727.55,28981.55,844582360,18185.99,64.137963
113,113,437311593,2019-09-23,BANKNIFTY,30039.40,30801.30,29776.30,30566.20,552171387,14401.90,73.352500
114,114,437321593,2019-09-24,BANKNIFTY,30432.00,30668.10,29889.55,30183.10,348810197,8157.62,68.616584
115,115,437331593,2019-09-25,BANKNIFTY,30029.05,30067.60,29470.10,29586.05,352814285,8112.37,61.716615
116,116,437341593,2019-09-26,BANKNIFTY,29640.55,30718.35,29627.00,30002.60,540435004,11367.60,64.485103
117,117,437351593,2019-09-27,BANKNIFTY,29974.95,30112.65,29711.35,29876.65,464096458,7011.82,62.955583
118,118,437381593,2019-09-30,BANKNIFTY,29674.80,29754.40,28943.45,29103.15,580252025,9447.47,54.185594
119,119,437391593,2019-10-01,BANKNIFTY,29226.15,29526.40,28077.35,28725.50,1187313940,15321.69,50.378474

### Bollinger Bands calculation
Calculate all the bollinger bands here

In [16]:
bb = ta.BBANDS(df[field].values,matype=ta.MA_Type.SMA)
df["BBUpper"] = bb[0]
df["BBMiddle"] = bb[1]
df["BBLower"] = bb[2]

# EMA Calculation

In [17]:
df["LONGEMA"]= ta.EMA(df["CLOSE"].values, timeperiod=200)
df["MEDIUMEMA"]= ta.EMA(df["CLOSE"].values, timeperiod=50)
df["SHORTEMA"]= ta.EMA(df["CLOSE"].values, timeperiod=7)

In [18]:
df.round({"Open":1, "TOTTRDQTY":0, "BBUpper":1, "BBMiddle":1, "BBLower":1, "SHORTEMA":1 })
df.dtypes

Unnamed: 0       int64
EODDATAID        int64
ADATE           object
SYMBOL          object
OPEN           float64
HIGH           float64
LOW            float64
CLOSE          float64
TOTTRDQTY        int64
TOTTRDVAL      float64
TIMESTAMP       object
TOTALTRADES    float64
RSI            float64
BBUpper        float64
BBMiddle       float64
BBLower        float64
LONGEMA        float64
MEDIUMEMA      float64
SHORTEMA       float64
dtype: object

In [19]:
df["trendangle"]=ta.LINEARREG_ANGLE (df[field].values, timeperiod=7)
df['trend'] = df.apply(lambda x: 'U' if x['trendangle']>0 else 'D', axis=1)

In [1]:
df["CDL3BLACKCROWS"]= ta.CDL3BLACKCROWS(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLDARKCLOUDCOVER"]= ta.CDLDARKCLOUDCOVER(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"],0)
df["CDLDOJI"]= ta.CDLDOJI(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLDOJISTAR"]= ta.CDLDOJISTAR(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLDRAGONFLYDOJI"]= ta.CDLDRAGONFLYDOJI(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLENGULFING"]= ta.CDLENGULFING(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLEVENINGDOJISTAR"]= ta.CDLEVENINGDOJISTAR(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"],0)
df["CDLEVENINGSTAR"]= ta.CDLEVENINGSTAR(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"],0)
df["CDLGAPSIDESIDEWHITE"]= ta.CDLGAPSIDESIDEWHITE(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLGRAVESTONEDOJI"]= ta.CDLGAPSIDESIDEWHITE(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLHAMMER"]= ta.CDLHAMMER(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLHANGINGMAN"]= ta.CDLHANGINGMAN(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])

df["CDLHARAMI"]= ta.CDLHARAMI(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLHARAMICROSS"]= ta.CDLHARAMICROSS(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLHIGHWAVE"]= ta.CDLHIGHWAVE(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLHIKKAKE"]= ta.CDLHIKKAKE(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLHIKKAKEMOD"]= ta.CDLHIKKAKEMOD(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLHOMINGPIGEON"]= ta.CDLHOMINGPIGEON(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLIDENTICAL3CROWS"]= ta.CDLIDENTICAL3CROWS(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLINNECK"]= ta.CDLINNECK(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLINVERTEDHAMMER"]= ta.CDLINVERTEDHAMMER(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLKICKING"]= ta.CDLKICKING(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLKICKINGBYLENGTH"]= ta.CDLKICKINGBYLENGTH(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLLADDERBOTTOM"]= ta.CDLLADDERBOTTOM(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLLONGLEGGEDDOJI"]= ta.CDLLONGLEGGEDDOJI(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLLONGLINE"]= ta.CDLLONGLINE(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLMATCHINGLOW"]= ta.CDLMATCHINGLOW(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])

df["CDLMATHOLD"]= ta.CDLMATHOLD(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLMORNINGDOJISTAR"]= ta.CDLMORNINGDOJISTAR(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLMORNINGSTAR"]= ta.CDLMORNINGSTAR(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLONNECK"]= ta.CDLONNECK(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLPIERCING"]= ta.CDLPIERCING(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLRICKSHAWMAN"]= ta.CDLRICKSHAWMAN(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLRISEFALL3METHODS"]= ta.CDLRISEFALL3METHODS(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLSEPARATINGLINES"]= ta.CDLSEPARATINGLINES(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLSHOOTINGSTAR"]= ta.CDLSHOOTINGSTAR(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLSHORTLINE"]= ta.CDLSHORTLINE(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLSPINNINGTOP"]= ta.CDLSPINNINGTOP(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])


df["CDLSTALLEDPATTERN"]= ta.CDLSTALLEDPATTERN(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLSTICKSANDWICH"]= ta.CDLSTICKSANDWICH(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLTAKURI"]= ta.CDLTAKURI(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLTASUKIGAP"]= ta.CDLTASUKIGAP(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLTHRUSTING"]= ta.CDLTHRUSTING(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLTRISTAR"]= ta.CDLTRISTAR(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLUNIQUE3RIVER"]= ta.CDLUNIQUE3RIVER(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLUPSIDEGAP2CROWS"]= ta.CDLUPSIDEGAP2CROWS(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])
df["CDLXSIDEGAP3METHODS"]= ta.CDLXSIDEGAP3METHODS(df["OPEN"], df["HIGH"], df["LOW"], df["CLOSE"])

df["OBV"]= ta.OBV(df["CLOSE"], df["TOTTRDQTY"])
df["AD"]= ta.AD(df["HIGH"], df["LOW"],df["CLOSE"], df["TOTTRDQTY"])
df["ADOSC"]= ta.ADOSC(df["HIGH"], df["LOW"],df["CLOSE"], df["TOTTRDQTY"],3,10)
df["ADOSC"]= ta.ADOSC(df["HIGH"], df["LOW"],df["CLOSE"], df["TOTTRDQTY"])


df["ADX14"]= ta.ADX( df["HIGH"], df["LOW"], df["CLOSE"],14)
df["ADXR14"]= ta.ADXR( df["HIGH"], df["LOW"], df["CLOSE"],14)
df["APO_12_26"]= ta.APO(df["CLOSE"])
df["AROON_14_Up"],df["AROON_14_Down"]= ta.AROON( df["HIGH"], df["LOW"])
df["RSI_14"]= ta.RSI(df["CLOSE"])
df["STOCH_k"], df["STOCH_d"]= ta.STOCH( df["HIGH"], df["LOW"], df["CLOSE"])
df["STOCHF_k"], df["STOCHF_d"]= ta.STOCHF( df["HIGH"], df["LOW"], df["CLOSE"])
df["STOCHRSI_k"],df["STOCHRSI_d"]= ta.STOCHRSI(df["CLOSE"])
df["TRIX_30"]= ta.TRIX(df["CLOSE"])
df["ULTOSC"]= ta.ULTOSC( df["HIGH"], df["LOW"], df["CLOSE"])
df["WILLR_14"]= ta.WILLR( df["HIGH"], df["LOW"], df["CLOSE"])
df["DX_14"]= ta.DX( df["HIGH"], df["LOW"], df["CLOSE"])
df["MACD"], df["MACD_Signal"], df["MACD_History"]= ta.MACD(df["CLOSE"])
df["MFI"]= ta.MFI( df["HIGH"], df["LOW"], df["CLOSE"], df["TOTTRDQTY"])
df["MOM"]= ta.MOM(df["CLOSE"])
df["ROC_10"]= ta.ROC(df["CLOSE"])
df["ROCP_10"]= ta.ROCP(df["CLOSE"])
df["ROCR_10"]= ta.ROCR(df["CLOSE"])

NameError: name 'ta' is not defined

In [21]:
df

,Unnamed: 0,EODDATAID,ADATE,SYMBOL,OPEN,HIGH,LOW,CLOSE,TOTTRDQTY,TOTTRDVAL,...,WILLR_14,DX_14,MACD,MACD_Signal,MACD_History,MFI,MOM,ROC_10,ROCP_10,ROCR_10
0,0,435571593,2019-04-02,BANKNIFTY,30450.10,30452.90,30155.85,30354.25,196482019,5205.38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,435581593,2019-04-03,BANKNIFTY,30440.85,30602.55,30036.25,30093.30,193071867,5203.95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,435591593,2019-04-04,BANKNIFTY,30147.30,30245.70,29809.90,29904.90,199631082,5460.27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,435601593,2019-04-05,BANKNIFTY,30002.85,30174.00,29850.00,30084.65,154141037,4130.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,435631593,2019-04-08,BANKNIFTY,30201.50,30232.05,29716.60,29845.30,147201421,3687.89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,435641593,2019-04-09,BANKNIFTY,29901.50,30165.05,29703.55,30113.85,165462138,4788.34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,435651593,2019-04-10,BANKNIFTY,29916.60,30155.75,29768.10,29803.50,165250173,9946.96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,435661593,2019-04-11,BANKNIFTY,29841.85,29852.25,29640.25,29786.10,108247929,3168.46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,435671593,2019-04-12,BANKNIFTY,29780.55,30000.95,29707.00,29938.55,104858970,3137.74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,435701593,2019-04-15,BANKNIFTY,29983.50,30163.10,29919.10,30104.25,90613632,3071.18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,435711593,2019-04-16,BANKNIFTY,30236.25,30590.95,30228.20,30531.35,117822281,4223.74,...,NaN,NaN,NaN,NaN,NaN,NaN,177.10,0.583444,0.005834,1.005834
11,11,435731593,2019-04-18,BANKNIFTY,30656.50,30669.80,30142.20,30223.40,141697748,4610.68,...,NaN,NaN,NaN,NaN,NaN,NaN,130.10,0.432322,0.004323,1.004323
12,12,435771593,2019-04-22,BANKNIFTY,30282.50,30289.90,29647.55,29687.95,132778018,4647.04,...,NaN,NaN,NaN,NaN,NaN,NaN,-216.95,-0.725466,-0.007255,0.992745
13,13,435781593,2019-04-23,BANKNIFTY,29761.95,29906.50,29455.45,29479.70,145857126,4502.93,...,-98.003047,NaN,NaN,NaN,NaN,NaN,-604.95,-2.010826,-0.020108,0.979892
14,14,435791593,2019-04-24,BANKNIFTY,29550.50,29914.85,29435.05,29860.80,129529258,4477.27,...,-65.519336,18.638808,NaN,NaN,NaN,38.231606,15.50,0.051934,0.000519,1.000519
15,15,435801593,2019-04-25,BANKNIFTY,29927.05,30057.70,29511.95,29561.35,201016367,6526.09,...,-89.771209,10.272747,NaN,NaN,NaN,38.146870,-552.50,-1.834704,-0.018347,0.981653
16,16,435811593,2019-04-26,BANKNIFTY,29764.85,30048.20,29563.15,30013.50,158188658,5736.29,...,-53.152460,10.272747,NaN,NaN,NaN,47.010284,210.00,0.704615,0.007046,1.007046
17,17,435851593,2019-04-30,BANKNIFTY,29920.40,29920.40,29550.05,29764.80,362563145,9257.75,...,-73.294189,10.940682,NaN,NaN,NaN,35.418090,-21.30,-0.071510,-0.000715,0.999285
18,18,435871593,2019-05-02,BANKNIFTY,29699.80,29919.35,29638.80,29708.60,242309997,6830.49,...,-77.845718,10.940682,NaN,NaN,NaN,44.600776,-229.95,-0.768073,-0.007681,0.992319
19,19,435881593,2019-05-03,BANKNIFTY,29811.65,30121.75,29795.10,29954.15,181379119,5248.10,...,-57.959101,2.115923,NaN,NaN,NaN,44.983261,-150.10,-0.498601,-0.004986,0.995014
20,20,435911593,2019-05-06,BANKNIFTY,29626.50,29757.40,29528.60,29618.45,188230212,4787.11,...,-85.146791,12.488256,NaN,NaN,NaN,44.567689,-912.90,-2.990041,-0.029900,0.970100
21,21,435921593,2019-05-07,BANKNIFTY,29749.55,29835.50,29244.25,29288.20,180581999,5340.05,...,-96.916979,24.839582,NaN,NaN,NaN,43.249128,-935.20,-3.094291,-0.030943,0.969057
22,22,435931593,2019-05-08,BANKNIFTY,29261.30,29261.30,28951.35,28994.40,179421775,4926.02,...,-97.494835,35.014169,NaN,NaN,NaN,37.722326,-693.55,-2.336133,-0.023361,0.976639
23,23,435941593,2019-05-09,BANKNIFTY,28893.95,29040.30,28784.65,28884.60,206029474,5196.87,...,-94.698035,39.993031,NaN,NaN,NaN,32.549385,-595.10,-2.018677,-0.020187,0.979813
24,24,435951593,2019-05-10,BANKNIFTY,28927.60,29202.85,28900.10,29040.50,223514610,6070.63,...,-86.428136,29.568713,NaN,NaN,NaN,35.025701,-820.30,-2.747080,-0.027471,0.972529
25,25,435981593,2019-05-13,BANKNIFTY,29026.65,29049.05,28621.10,28659.95,253600119,5356.35,...,-97.671980,38.089979,NaN,NaN,NaN,33.747065,-901.40,-3.049252,-0.030493,0.969507
26,26,435991593,2019-05-14,BANKNIFTY,28718.75,29058.30,28582.60,28829.20,256593306,6110.47,...,-83.978170,39.183436,NaN,NaN,NaN,41.039333,-1184.30,-3.945891,-0.039459,0.960541
27,27,436001593,2019-05-15,BANKNIFTY,28925.45,28983.15,28555.15,28616.45,218778407,5126.91,...,-96.087068,39.997163,NaN,NaN,NaN,40.118553,-1148.35,-3.858081,-0.038581,0.961419
28,28,436011593,2019-05-16,BANKNIFTY,28625.90,28947.60,28525.45,28855.30,189440058,4501.11,...,-79.336591,40.918267,NaN,NaN,NaN,41.193385,-853.30,-2.872232,-0.028722,0.971278
29,29,436021593,2019-05-17,BANKNIFTY,28881.40,29559.45,28856.00,29450.15,257111157,6489.10,...,-42.072292,5.117932,NaN,NaN,NaN,48.790537,-504.00,-1.682572,-0.016826,0.983174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,89,436901593,2019-08-13,BANKNIFTY,28356.80,28358.85,27683.50,27729.10,335809590,5984.53,...,-84.587805,44.297348,-674.667121,-621.783210,-52.883910,43.505813,-1566.80,-5.348189,-0.053482,0.946518
90,90,436911593,2019-08-14,BANKNIFTY,27885.50,28107.05,27726.65,28019.20,290413445,5104.33,...,-71.422088,44.297348,-654.027853,-628.232139,-25.795714,49.531233,-772.40,-2.682727,-0.026827,0.973173
91,91,436971593,2019-08-20,BANKNIFTY,28163.55,28215.40,27839.65,27982.45,288236399,5073.04,...,-73.089927,39.410917,-633.335802,-629.252871,-4.082930,49.313256,-893.55,-3.094438,-0.030944,0.969056
92,92,436981593,2019-08-21,BANKNIFTY,28021.00,28098.90,27666.20,27719.05,358841104,5315.64,...,-85.043908,42.752992,-630.918544,-629.586006,-1.332539,40.859843,-648.20,-2.285029,-0.022850,0.977150
93,93,436991593,2019-08-22,BANKNIFTY,27690.05,27690.05,26975.55,27034.20,465070847,6452.46,...,-97.704276,53.703586,-676.466636,-638.962132,-37.504504,32.782503,-1170.75,-4.150867,-0.041509,0.958491
94,94,437001593,2019-08-23,BANKNIFTY,26835.35,27207.30,26560.60,26958.65,485538647,7843.57,...,-83.545874,58.802505,-710.470222,-653.263750,-57.206472,31.721725,-689.40,-2.493485,-0.024935,0.975065
95,95,437031593,2019-08-26,BANKNIFTY,27663.95,27995.25,26859.35,27951.35,519219181,8927.81,...,-38.437873,29.610797,-649.824937,-652.575987,2.751050,41.111183,-70.75,-0.252479,-0.002525,0.997475
96,96,437041593,2019-08-27,BANKNIFTY,28106.30,28277.70,27960.80,28126.15,386839458,7802.00,...,-23.338149,21.022706,-580.961254,-638.253041,57.291787,48.003158,424.10,1.530934,0.015309,1.015309
97,97,437051593,2019-08-28,BANKNIFTY,28080.25,28095.55,27634.65,27804.30,384111651,6674.30,...,-39.098499,27.034876,-546.062228,-619.814878,73.752650,47.442294,-306.15,-1.089097,-0.010891,0.989109
98,98,437061593,2019-08-29,BANKNIFTY,27694.95,27719.05,27239.95,27305.20,377438481,7339.26,...,-63.538428,33.620507,-552.311000,-606.314102,54.003102,47.075552,-1126.70,-3.962802,-0.039628,0.960372
99,99,437071593,2019-08-30,BANKNIFTY,27407.90,27586.50,27121.95,27427.85,427077225,8056.50,...,-57.532503,35.494962,-541.128574,-593.276997,52.148423,40.414964,-301.25,-1.086404,-0.010864,0.989136
100,100,437111593,2019-09-03,BANKNIFTY,27239.20,27247.05,26742.60,26824.15,392427883,6171.33,...,-87.094484,41.239674,-574.359111,-589.493419,15.134309,40.214737,-1195.05,-4.265111,-0.042651,0.957349
101,101,437121593,2019-09-04,BANKNIFTY,26785.95,27278.70,26641.35,27123.85,309520214,5990.87,...,-72.418774,42.706306,-569.941336,-585.583003,15.641667,40.163798,-858.60,-3.068352,-0.030684,0.969316
102,102,437131593,2019-09-05,BANKNIFTY,27086.95,27243.95,26815.40,26919.70,327083693,5826.31,...,-80.030585,42.706306,-576.270529,-583.720508,7.449979,33.853582,-799.35,-2.883757,-0.028838,0.971162
103,103,437141593,2019-09-06,BANKNIFTY,26986.50,27311.05,26950.55,27247.90,251986487,4874.57,...,-59.973211,40.020192,-548.480916,-576.672590,28.191673,39.185789,213.70,0.790480,0.007905,1.007905
104,104,437171593,2019-09-09,BANKNIFTY,27240.35,27565.55,26993.90,27504.65,286110458,5197.20,...,-45.020674,30.023570,-499.976452,-561.333362,61.356911,39.063096,546.00,2.025324,0.020253,1.020253
105,105,437191593,2019-09-11,BANKNIFTY,27639.05,27829.65,27551.65,27776.20,467414755,6677.77,...,-29.206220,20.416030,-434.614532,-535.989596,101.375064,41.059004,-175.15,-0.626624,-0.006266,0.993734
106,106,437201593,2019-09-12,BANKNIFTY,27870.80,28062.30,27764.70,27818.50,377820739,6469.22,...,-26.742764,12.527974,-375.077820,-503.807241,128.729421,47.949937,-307.65,-1.093822,-0.010938,0.989062
107,107,437211593,2019-09-13,BANKNIFTY,27772.00,28126.85,27573.45,28098.75,438497830,6752.69,...,-10.421641,17.322609,-301.801732,-463.406139,161.604407,56.294096,294.45,1.059009,0.010590,1.010590
108,108,437241593,2019-09-16,BANKNIFTY,27868.00,28066.70,27798.85,27855.00,234062573,4463.98,...,-25.831882,17.322609,-260.396799,-422.804271,162.407472,58.872279,549.80,2.013536,0.020135,1.020135
109,109,437251593,2019-09-17,BANKNIFTY,27765.10,27851.40,27047.95,27131.75,277762547,5449.45,...,-70.030861,33.836664,-282.684709,-394.780359,112.095650,51.245903,-296.10,-1.079560,-0.010796,0.989204
110,110,437261593,2019-09-18,BANKNIFTY,27304.70,27414.45,27088.80,27172.65,307775512,5314.41,...,-64.234265,33.836664,-293.662591,-374.556805,80.894214,44.052172,348.50,1.299202,0.012992,1.012992
111,111,437271593,2019-09-19,BANKNIFTY,27175.45,27175.45,26643.00,26757.65,450436905,6050.19,...,-92.170986,41.835913,-332.022326,-366.049909,34.027583,43.593870,-366.20,-1.350103,-0.013501,0.986499
112,112,437281593,2019-09-20,BANKNIFTY,26878.65,29418.95,26727.55,28981.55,844582360,18185.99,...,-15.747408,14.311133,-180.887391,-329.017406,148.130015,55.740531,2061.85,7.659261,0.076593,1.076593
113,113,437311593,2019-09-23,BANKNIFTY,30039.40,30801.30,29776.30,30566.20,552171387,14401.90,...,-5.651510,32.136991,65.995391,-250.014846,316.010238,64.822401,3318.30,12.178186,0.121782,1.121782
114,114,437321593,2019-09-24,BANKNIFTY,30432.00,30668.10,29889.55,30183.10,348810197,8157.62,...,-14.860756,32.136991,228.109305,-154.390016,382.499321,64.831169,2678.45,9.738172,0.097382,1.097382
115,115,437331593,2019-09-25,BANKNIFTY,30029.05,30067.60,29470.10,29586.05,352814285,8112.37,...,-29.224683,23.123393,304.894174,-62.533178,367.427352,58.574945,1809.85,6.515830,0.065158,1.065158
116,116,437341593,2019-09-26,BANKNIFTY,29640.55,30718.35,29627.00,30002.60,540435004,11367.60,...,-19.207368,30.988651,394.807741,28.935006,365.872736,65.881080,2184.10,7.851250,0.078513,1.078513
117,117,437351593,2019-09-27,BANKNIFTY,29974.95,30112.65,29711.35,29876.65,464096458,7011.82,...,-22.236250,30.988651,450.706317,113.289268,337.417049,59.133136,1777.90,6.327328,0.063273,1.063273
118,118,437381593,2019-09-30,BANKNIFTY,29674.80,29754.40,28943.45,29103.15,580252025,9447.47,...,-40.837602,14.900683,427.661540,176.163722,251.497817,51.746557,1248.15,4.480883,0.044809,1.044809

### Save back in to DB

In [23]:
df.to_csv("processed.csv")